name: Sync fork

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/anidl/multi-downloader-nx
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
