name: Sync Fork and auto-release

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: someonelike-u
          base: master
          head: master
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Latest Version from Upstream
        id: get_version
        run: |
          LATEST_COMMIT=$(git rev-list --tags --max-count=1)
          LATEST_TAG=$(git describe --tags "$LATEST_COMMIT" 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
      - name: Generate Forked Version
        id: fork_version
        run: |
          ORIGINAL_VERSION=${{ env.LATEST_TAG }}
          FORKED_VERSION="${ORIGINAL_VERSION}.1"
          echo "FORKED_VERSION=$FORKED_VERSION" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.FORKED_VERSION }}
          name: "Release ${{ env.FORKED_VERSION }}"
          body: "Automated release based on upstream version ${{ env.LATEST_TAG }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
