name: Sync Fork and auto-release

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: someonelike-u
          base: master
          head: master
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Latest Version from Upstream
        id: get_version
        run: |
          git fetch upstream --tags --force
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)

          if [[ -z "$LATEST_TAG" ]]; then
            LATEST_TAG="v0.0.0"
          fi

          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest upstream tag: $LATEST_TAG"
      - name: Generate Forked Version
        id: fork_version
        run: |
          ORIGINAL_VERSION=${{ env.LATEST_TAG }}
          FORKED_VERSION="${ORIGINAL_VERSION}.1"
          echo "FORKED_VERSION=$FORKED_VERSION" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.FORKED_VERSION }}
          name: "Release ${{ env.FORKED_VERSION }}"
          body: "Automated release based on upstream version ${{ env.LATEST_TAG }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
